name: hello
on: push
jobs: 
    say-hello-job:
        runs-on: ubuntu-latest
        steps: 
        -   name: checkoit repo code
            uses: actiond/checkout@v3 
        -   run: echo "$(cat hello_world.txt)"