name: hello
on: push
jobs: 
    say-hello-job:
        runs-on: ubuntu-latest
        steps: 
        -   name: checkoit repo code
            uses: actions/checkout@v3 
        -   run: echo "Append current date $(date)" >> hello_world.txt && cat hello_world.txt

        